"""LinkedIn play (warm) — Phase 5. MANUAL-EXECUTION ONLY.

⛔ ABSOLUTE PROHIBITION: The agent performs ZERO LinkedIn calls of any kind.
   No login. No search. No scraping. No API. No browser automation.
   All output is draft text for the human to copy-paste and execute manually
   in their own LinkedIn browser session. This constraint is permanent.

This module produces manual-execution drafts from PUBLIC / ATS sources only:
  * a targeted boolean LinkedIn search string (built deterministically),
  * a contact list from the PUBLIC job posting (emails, named contacts),
  * a drafted connection note (<=300 chars, grounded in a scored match point)
    and a follow-up message, generated by the LLM in the user's voice.

The output is a checklist clearly labelled for manual execution.
"""

from __future__ import annotations

import logging
import re
from typing import Any

from pydantic import BaseModel, Field

from agent.llm.client import parse_structured, resolve_node

logger = logging.getLogger(__name__)

_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
_NAME_CUE_RE = re.compile(
    r"(?:contact|reach out to|email|questions to|speak (?:with|to))\s+"
    r"([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)",
)
_REMOTE_SKIP_RE = re.compile(r"^(remote|europe|worldwide|global|anywhere)\b", re.I)
_AI_TITLE_RE = re.compile(r"\b(ai|ml|machine[\s-]learning|genai|gen[\s-]ai|data|llm|nlp)\b", re.I)
_ARCH_TITLE_RE = re.compile(r"\b(architect|architecture|platform|infrastructure|cloud)\b", re.I)

_CONNECTION_NOTE_LIMIT = 300

_ROLE_TERMS: dict[str, str] = {
    "ai": (
        '("head of AI" OR "head of data" OR "AI engineering manager" '
        'OR "talent acquisition" OR "technical recruiter")'
    ),
    "arch": (
        '("head of architecture" OR "principal architect" '
        'OR "engineering manager" OR "talent acquisition" OR "technical recruiter")'
    ),
    "default": (
        '("engineering manager" OR "hiring manager" '
        'OR "talent acquisition" OR "technical recruiter")'
    ),
}

_HINT_TITLES: dict[str, str] = {
    "ai":      "Head of AI / Head of Data / AI Engineering Manager",
    "arch":    "Head of Architecture / Principal Architect / Engineering Manager",
    "default": "Engineering Manager / Hiring Manager",
}


class Outreach(BaseModel):
    connection_note: str = Field(description="LinkedIn connection note, <=300 characters.")
    follow_up: str = Field(description="Longer follow-up message once connected.")


def _title_domain(title: str) -> str:
    if _AI_TITLE_RE.search(title):
        return "ai"
    if _ARCH_TITLE_RE.search(title):
        return "arch"
    return "default"


def boolean_search_string(job: dict[str, Any]) -> str:
    """A boolean search string the user can paste into LinkedIn's people search.

    Targeted by company + role domain (inferred from job title) + location city.
    Built deterministically from the public posting — NO LLM call.
    ⛔ The user runs this search themselves — the agent never touches LinkedIn.
    """
    company = (job.get("company") or "").strip()
    title = (job.get("title") or "").strip()
    location = (job.get("location") or "").strip()
    domain = _title_domain(title)

    clauses: list[str] = []
    if company:
        clauses.append(f'"{company}"')
    clauses.append(_ROLE_TERMS[domain])

    # city = part before first comma; skip if remote/global/europe
    if location:
        city = location.split(",")[0].strip()
        if city and not _REMOTE_SKIP_RE.match(city):
            clauses.append(f'"{city}"')

    return " AND ".join(clauses)


def public_contacts(job: dict[str, Any]) -> list[dict[str, str]]:
    """Contacts derivable from the PUBLIC posting only (no LinkedIn).

    Returns a list of {type, value, source} dicts:
      * type "email"       — email address found in the JD
      * type "name"        — named contact from a contact cue in the JD
      * type "search_hint" — titles to look for on company/LinkedIn pages (always present)
    """
    jd = job.get("jd_text") or ""
    title = job.get("title") or ""
    contacts: list[dict[str, str]] = []
    seen: set[str] = set()

    for email in _EMAIL_RE.findall(jd):
        key = email.lower()
        if key in seen:
            continue
        seen.add(key)
        contacts.append({"type": "email", "value": email, "source": "job posting"})

    for m in _NAME_CUE_RE.finditer(jd):
        name = m.group(1).strip()
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        contacts.append({"type": "name", "value": name, "source": "named in posting"})

    hint_titles = _HINT_TITLES[_title_domain(title)]
    contacts.append({
        "type": "search_hint",
        "value": f"Look for: {hint_titles}, and the recruiter who posted the role",
        "source": "suggested — search on company pages / LinkedIn",
    })

    return contacts


def _outreach(
    profile: dict[str, Any],
    job: dict[str, Any],
    client: Any | None,
    match_points: list[str] | None = None,
) -> Outreach:
    """Generate connection note + follow-up via the configured LLM.

    match_points (from the scoring step) are passed in so the LLM can ground
    the note in a genuine, already-verified match — avoiding fabrication and
    avoiding a second LLM call to re-derive them.
    ⛔ The generated text is for manual copy-paste — the agent never sends it.
    """
    personal = profile.get("personal", {})
    cv = profile.get("cv_content", {})
    style = profile.get("letter_style", {})
    provider, model = resolve_node(profile, "outreach")

    jd_snippet = (job.get("jd_text") or "")[:2000]

    match_block = ""
    if match_points:
        formatted = "\n".join(f"  - {p}" for p in match_points[:3])
        match_block = (
            f"\nSCORED MATCH POINTS (from the scoring step — use one of these, "
            f"never invent experience not in the profile):\n{formatted}\n"
        )

    system = (
        "You draft short, genuine LinkedIn outreach in the candidate's voice. "
        "No flattery, no buzzwords. The connection note MUST be <= "
        f"{_CONNECTION_NOTE_LIMIT} characters AND must reference ONE specific, "
        "genuine match point between the candidate and the role — "
        "use the scored match points if provided; never invent experience "
        "the candidate doesn't have.\n\n"
        f"CANDIDATE: {personal.get('name')} — {(cv.get('summary') or '').strip()[:300]}\n"
        f"VOICE: {(style.get('voice_notes') or '').strip()}"
        f"{match_block}\n"
        "Respond with ONLY a JSON object: connection_note (string), follow_up (string)."
    )
    user = (
        f"ROLE: {job.get('title')} at {job.get('company')} "
        f"({job.get('location') or ''})\n\n"
        f"JD EXCERPT:\n{jd_snippet}\n\n"
        "Draft a connection note (must cite one specific match point) and a follow-up."
    )
    return parse_structured(
        provider=provider, model=model, system=system, user=user,
        schema_model=Outreach, client=client, max_tokens=600,
    )


def build_linkedin_play(
    profile: dict[str, Any],
    job: dict[str, Any],
    *,
    client: Any | None = None,
    match_points: list[str] | None = None,
) -> dict[str, Any]:
    """Return the manual-execution LinkedIn play for one role.

    ⛔ MANUAL-ONLY: all output is draft text; the agent never touches LinkedIn.
    """
    outreach = _outreach(profile, job, client, match_points=match_points)
    note = outreach.connection_note.strip()[:_CONNECTION_NOTE_LIMIT]
    return {
        "manual_only": True,
        "search_string": boolean_search_string(job),
        "contacts": public_contacts(job),
        "connection_note": note,
        "follow_up": outreach.follow_up.strip(),
    }


def render_play_email(job: dict[str, Any], play: dict[str, Any]) -> str:
    """Format the play as a manual-action checklist for the reply email."""
    contacts = play.get("contacts", [])
    contact_lines = (
        "\n".join(f"    - {c['value']} ({c['source']})" for c in contacts)
        if contacts else "    - none found in the public posting — use the search string above"
    )
    return (
        f"LinkedIn play for: {job.get('title')} — {job.get('company')}\n"
        "DO THESE MANUALLY IN YOUR OWN LINKEDIN BROWSER SESSION. "
        "The agent does not touch LinkedIn.\n\n"
        "1) Paste this boolean search into LinkedIn people search:\n"
        f"    {play.get('search_string')}\n\n"
        "2) Candidate contacts from the public posting:\n"
        f"{contact_lines}\n\n"
        "3) Connection note (<=300 chars) — copy/paste:\n"
        f"    {play.get('connection_note')}\n\n"
        "4) Follow-up message once connected:\n"
        f"    {play.get('follow_up')}\n"
    )
